services:
  server:
    container_name: go-advaced-metrics-server
    build: 
      context: ./docker/go
    user: 1000:1000
    volumes:
      - .:/go/app
      - ${HOME}:${HOME}:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    ports:
      - 8080:8080
    command: go run cmd/server/main.go -a :8080
