services:
  server:
    container_name: go-advaced-metrics-server
    build: 
      context: ./docker/go
    depends_on:
      - postgres-db
    user: 1000:1000
    volumes:
      - .:/go/app
      - ${HOME}:${HOME}:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    ports:
      - 8080:8080
    networks:
      - metrics
    command: go run cmd/server/main.go -a :8080 -r -d postgres://metrics_usr:password@postgres-db:5432/metrics -k secret -crypto-key data/rsa/private-key.pem --audit-file data/server/audit.log -t 172.19.0.0/24

  # # for profiling
  # agent:
  #   container_name: go-advaced-metrics-agent
  #   build: 
  #     context: ./docker/go
  #   depends_on:
  #     - server
  #   volumes:
  #     - .:/go/app
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - metrics
  #   command: go run cmd/agent/main.go -g server:50051 -k secret -crypto-key data/rsa/public-key.pem -p 1 -r 2 -pprof-addr :9090

  postgres-db:
      container_name: go-advaced-metrics-postgres-db
      working_dir: /app
      image: postgres:13.0-alpine
      environment:
          POSTGRES_USER: metrics_usr
          POSTGRES_PASSWORD: password
          POSTGRES_DB: metrics
      ports:
          - '5433:5432'
      networks:
          - metrics
      volumes:
          - server-postgres:/var/lib/postgresql/data

networks:
  metrics:
      name: metrics
      driver: bridge

volumes:
  server-postgres: